config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios

  resources :home, only: [:index]

  authenticate :usuario do
    resources :detalle_sumistros, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :municipios, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :mesas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :rols, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :departamentos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :permisos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :nombre_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :suministros, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :unidad_medidas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :empresas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_menu_dia, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :menu_dia, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :clientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :estado_pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :empleados, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :personas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :departamentos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :ciudads, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :ingredientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tipo_ingredientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :imagens, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tipo_platos, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'welcome/index'
  root 'static_pages#home'

end

app/models/detalle_sumistro.rb
class DetalleSumistro < ActiveRecord::Base
end

app/controllers/detalle_sumistros_controller.rb
class DetalleSumistrosController < ApplicationController
  before_action :set_detalle_sumistro, only: [:show, :edit, :update, :destroy]

  # GET /detalle_sumistros
  # GET /detalle_sumistros.json
  def index
    @detalle_sumistros = DetalleSumistro.all
  end

  # GET /detalle_sumistros/1
  # GET /detalle_sumistros/1.json
  def show
  end

  # GET /detalle_sumistros/new
  def new
    @detalle_sumistro = DetalleSumistro.new
  end

  # GET /detalle_sumistros/1/edit
  def edit
  end

  # POST /detalle_sumistros
  # POST /detalle_sumistros.json
  def create
    @detalle_sumistro = DetalleSumistro.new(detalle_sumistro_params)

    respond_to do |format|
      if @detalle_sumistro.save
        format.html { redirect_to @detalle_sumistro, notice: 'Detalle sumistro was successfully created.' }
        format.json { render :show, status: :created, location: @detalle_sumistro }
      else
        format.html { render :new }
        format.json { render json: @detalle_sumistro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalle_sumistros/1
  # PATCH/PUT /detalle_sumistros/1.json
  def update
    respond_to do |format|
      if @detalle_sumistro.update(detalle_sumistro_params)
        format.html { redirect_to @detalle_sumistro, notice: 'Detalle sumistro was successfully updated.' }
        format.json { render :show, status: :ok, location: @detalle_sumistro }
      else
        format.html { render :edit }
        format.json { render json: @detalle_sumistro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalle_sumistros/1
  # DELETE /detalle_sumistros/1.json
  def destroy
    @detalle_sumistro.destroy
    respond_to do |format|
      format.html { redirect_to detalle_sumistros_url, notice: 'Detalle sumistro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalle_sumistro
      @detalle_sumistro = DetalleSumistro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detalle_sumistro_params
      params.require(:detalle_sumistro).permit(:Cantidad, :PrecioUnitario, :IVA, :Subtotal, :FechaVencimiento, :Ingrediente_id, :Suministro_id, :UnidadMedida_id)
    end
end

app/helpers/detalle_sumistros_helper.rb
module DetalleSumistrosHelper
end

app/views/detalle_sumistros/_form.html.erb
<%= form_for @detalle_sumistro, :html => { :class => "form-horizontal detalle_sumistro" } do |f| %>

    <% if @detalle_sumistro.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@detalle_sumistro.errors.count, "error") %> prohibited this detalle_sumistro from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @detalle_sumistro.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Cantidad, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Cantidad, :class => 'form-control' %>
    </div>
    <%= error_span(@detalle_sumistro[:Cantidad]) %>
  </div>
  <div class="control-group">
    <%= f.label :PrecioUnitario, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :PrecioUnitario, :class => 'form-control' %>
    </div>
    <%= error_span(@detalle_sumistro[:PrecioUnitario]) %>
  </div>
  <div class="control-group">
    <%= f.label :IVA, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :IVA, :class => 'form-control' %>
    </div>
    <%= error_span(@detalle_sumistro[:IVA]) %>
  </div>
  <div class="control-group">
    <%= f.label :Subtotal, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Subtotal, :class => 'form-control' %>
    </div>
    <%= error_span(@detalle_sumistro[:Subtotal]) %>
  </div>
  <div class="control-group">
    <%= f.label :FechaVencimiento, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :FechaVencimiento, :class => 'form-control' %>
    </div>
    <%= error_span(@detalle_sumistro[:FechaVencimiento]) %>
  </div>
  <div class="control-group">
    <%= f.label :Ingrediente_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :Ingrediente_id, Ingrediente.all.collect { |p| [ p.NombreIngrediente, p.id ] }, include_blank: true, :class => 'form-control'%>
    </div>
    <%= error_span(@detalle_sumistro[:Ingrediente_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :Suministro_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :Suministro_id, Suministro.all.collect { |p| [ p.NombreIngrediente, p.id ] }, include_blank: true, :class => 'form-control'%>
      <%= f.text_field :Suministro_id, :class => 'form-control' %>
    </div>
    <%= error_span(@detalle_sumistro[:Suministro_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :UnidadMedida_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :UnidadMedida_id, :class => 'form-control' %>
    </div>
    <%= error_span(@detalle_sumistro[:UnidadMedida_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            detalle_sumistros_path, :class => 'btn btn-default' %>

<% end %>

app/views/detalle_sumistros/edit.html.erb
<%- model_class = DetalleSumistro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/detalle_sumistros/index.html.erb
<%- model_class = DetalleSumistro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Cantidad) %></th>
      <th><%= model_class.human_attribute_name(:PrecioUnitario) %></th>
      <th><%= model_class.human_attribute_name(:IVA) %></th>
      <th><%= model_class.human_attribute_name(:Subtotal) %></th>
      <th><%= model_class.human_attribute_name(:FechaVencimiento) %></th>
      <th><%= model_class.human_attribute_name(:Ingrediente_id) %></th>
      <th><%= model_class.human_attribute_name(:Suministro_id) %></th>
      <th><%= model_class.human_attribute_name(:UnidadMedida_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @detalle_sumistros.each do |detalle_sumistro| %>
      <tr>
        <td><%= link_to detalle_sumistro.id, detalle_sumistro_path(detalle_sumistro) %></td>
        <td><%= detalle_sumistro.Cantidad %></td>
        <td><%= detalle_sumistro.PrecioUnitario %></td>
        <td><%= detalle_sumistro.IVA %></td>
        <td><%= detalle_sumistro.Subtotal %></td>
        <td><%= detalle_sumistro.FechaVencimiento %></td>
        <td><%= detalle_sumistro.Ingrediente_id %></td>
        <td><%= detalle_sumistro.Suministro_id %></td>
        <td><%= detalle_sumistro.UnidadMedida_id %></td>
        <td><%= detalle_sumistro.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_detalle_sumistro_path(detalle_sumistro), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      detalle_sumistro_path(detalle_sumistro),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_detalle_sumistro_path,
            :class => 'btn btn-primary' %>

app/views/detalle_sumistros/new.html.erb
<%- model_class = DetalleSumistro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/detalle_sumistros/show.html.erb
<%- model_class = DetalleSumistro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Cantidad) %>:</strong></dt>
  <dd><%= @detalle_sumistro.Cantidad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:PrecioUnitario) %>:</strong></dt>
  <dd><%= @detalle_sumistro.PrecioUnitario %></dd>
  <dt><strong><%= model_class.human_attribute_name(:IVA) %>:</strong></dt>
  <dd><%= @detalle_sumistro.IVA %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Subtotal) %>:</strong></dt>
  <dd><%= @detalle_sumistro.Subtotal %></dd>
  <dt><strong><%= model_class.human_attribute_name(:FechaVencimiento) %>:</strong></dt>
  <dd><%= @detalle_sumistro.FechaVencimiento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Ingrediente_id) %>:</strong></dt>
  <dd><%= @detalle_sumistro.Ingrediente_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Suministro_id) %>:</strong></dt>
  <dd><%= @detalle_sumistro.Suministro_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:UnidadMedida_id) %>:</strong></dt>
  <dd><%= @detalle_sumistro.UnidadMedida_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              detalle_sumistros_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_detalle_sumistro_path(@detalle_sumistro), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              detalle_sumistro_path(@detalle_sumistro),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>