config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios

  resources :home, only: [:index]

  authenticate :usuario do
    resources :detalle_sumistros, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :municipios, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :mesas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :rols, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :departamentos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :permisos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :nombre_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :suministros, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :unidad_medidas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :empresas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_menu_dia, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :menu_dia, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :clientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :estado_pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :empleados, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :personas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :departamentos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :ciudads, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :ingredientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tipo_ingredientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :imagens, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tipo_platos, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'welcome/index'
  root 'static_pages#home'

end

app/models/unidad_medida.rb
class UnidadMedida < ActiveRecord::Base
  validates :NombreCompleto, presence: { message: " es requerido"}
  validates :Unidad, presence: { message: " es requerido"}
end

app/controllers/unidad_medidas_controller.rb
class UnidadMedidasController < ApplicationController
  before_action :set_unidad_medida, only: [:show, :edit, :update, :destroy]

  # GET /unidad_medidas
  # GET /unidad_medidas.json
  def index
    @unidad_medidas = UnidadMedida.all
  end

  # GET /unidad_medidas/1
  # GET /unidad_medidas/1.json
  def show
  end

  # GET /unidad_medidas/new
  def new
    @unidad_medida = UnidadMedida.new
  end

  # GET /unidad_medidas/1/edit
  def edit
  end

  # POST /unidad_medidas
  # POST /unidad_medidas.json
  def create
    @unidad_medida = UnidadMedida.new(unidad_medida_params)

    respond_to do |format|
      if @unidad_medida.save
        format.html { redirect_to @unidad_medida, notice: 'Unidad medida was successfully created.' }
        format.json { render :show, status: :created, location: @unidad_medida }
      else
        format.html { render :new }
        format.json { render json: @unidad_medida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidad_medidas/1
  # PATCH/PUT /unidad_medidas/1.json
  def update
    respond_to do |format|
      if @unidad_medida.update(unidad_medida_params)
        format.html { redirect_to @unidad_medida, notice: 'Unidad medida was successfully updated.' }
        format.json { render :show, status: :ok, location: @unidad_medida }
      else
        format.html { render :edit }
        format.json { render json: @unidad_medida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidad_medidas/1
  # DELETE /unidad_medidas/1.json
  def destroy
    @unidad_medida.destroy
    respond_to do |format|
      format.html { redirect_to unidad_medidas_url, notice: 'Unidad medida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidad_medida
      @unidad_medida = UnidadMedida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unidad_medida_params
      params.require(:unidad_medida).permit(:Unidad, :NombreCompleto)
    end
end

app/helpers/unidad_medidas_helper.rb
module UnidadMedidasHelper
end

app/views/unidad_medidas/_form.html.erb
<%= form_for @unidad_medida, :html => { :class => "form-horizontal unidad_medida" } do |f| %>

    <% if @unidad_medida.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@unidad_medida.errors.count, "error") %> prohibited this unidad_medida from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @unidad_medida.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Unidad, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Unidad, :class => 'form-control' %>
    </div>
    <%= error_span(@unidad_medida[:Unidad]) %>
  </div>
  <div class="control-group">
    <%= f.label :NombreCompleto, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :NombreCompleto, :class => 'form-control' %>
    </div>
    <%= error_span(@unidad_medida[:NombreCompleto]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            unidad_medidas_path, :class => 'btn btn-default' %>

<% end %>

app/views/unidad_medidas/edit.html.erb
<%- model_class = UnidadMedida -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/unidad_medidas/index.html.erb
<%- model_class = UnidadMedida -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Unidad) %></th>
      <th><%= model_class.human_attribute_name(:NombreCompleto) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @unidad_medidas.each do |unidad_medida| %>
      <tr>
        <td><%= link_to unidad_medida.id, unidad_medida_path(unidad_medida) %></td>
        <td><%= unidad_medida.Unidad %></td>
        <td><%= unidad_medida.NombreCompleto %></td>
        <td><%=l unidad_medida.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_unidad_medida_path(unidad_medida), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      unidad_medida_path(unidad_medida),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_unidad_medida_path,
            :class => 'btn btn-primary' %>

app/views/unidad_medidas/new.html.erb
<%- model_class = UnidadMedida -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/unidad_medidas/show.html.erb
<%- model_class = UnidadMedida -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Unidad) %>:</strong></dt>
  <dd><%= @unidad_medida.Unidad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:NombreCompleto) %>:</strong></dt>
  <dd><%= @unidad_medida.NombreCompleto %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              unidad_medidas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unidad_medida_path(@unidad_medida), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unidad_medida_path(@unidad_medida),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>