config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios

  resources :home, only: [:index]

  authenticate :usuario do
    resources :detalle_sumistros, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :municipios, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :mesas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :rols, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :departamentos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :permisos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :nombre_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :suministros, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :unidad_medidas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :empresas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_menu_dia, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :menu_dia, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :clientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :estado_pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :empleados, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :personas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :departamentos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :ciudads, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :ingredientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tipo_ingredientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :imagens, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tipo_platos, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'welcome/index'
  root 'static_pages#home'

end

app/models/permiso.rb
class Permiso < ActiveRecord::Base
  validates :NombrePermiso, presence: { message: " es requerido"}
end

app/controllers/permisos_controller.rb
class PermisosController < ApplicationController
  before_action :set_permiso, only: [:show, :edit, :update, :destroy]

  # GET /permisos
  # GET /permisos.json
  def index
    @permisos = Permiso.all
  end

  # GET /permisos/1
  # GET /permisos/1.json
  def show
  end

  # GET /permisos/new
  def new
    @permiso = Permiso.new
  end

  # GET /permisos/1/edit
  def edit
  end

  # POST /permisos
  # POST /permisos.json
  def create
    @permiso = Permiso.new(permiso_params)

    respond_to do |format|
      if @permiso.save
        format.html { redirect_to @permiso, notice: 'Permiso was successfully created.' }
        format.json { render :show, status: :created, location: @permiso }
      else
        format.html { render :new }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permisos/1
  # PATCH/PUT /permisos/1.json
  def update
    respond_to do |format|
      if @permiso.update(permiso_params)
        format.html { redirect_to @permiso, notice: 'Permiso was successfully updated.' }
        format.json { render :show, status: :ok, location: @permiso }
      else
        format.html { render :edit }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permisos/1
  # DELETE /permisos/1.json
  def destroy
      @permiso.destroy
      respond_to do |format|
        format.html { redirect_to permisos_url, notice: 'Permiso was successfully destroyed.' }
        format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permiso
      @permiso = Permiso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permiso_params
      params.require(:permiso).permit(:NombrePermiso, :Eliminar, :Modificar, :Ver, :rols_id)
    end
end

app/helpers/permisos_helper.rb
module PermisosHelper
end

app/views/permisos/_form.html.erb
<%= form_for @permiso, :html => { :class => "form-horizontal permiso" } do |f| %>

<% if @permiso.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@permiso.errors.count, "error") %> prohibited this permiso from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
    <% @permiso.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>
<table>
  <tr>
    <td class="control-group">
      <%= f.label :NombrePermiso, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :NombrePermiso, :class => 'form-control' %>
      </div>
      <%= error_span(@permiso[:NombrePermiso]) %>
    </td>
    <td class="control-group">
      <%= f.label :Eliminar, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :Eliminar, :class => 'form-control' %>
      </div>
      <%= error_span(@permiso[:Eliminar]) %>
    </td>
    <td class="control-group">
      <%= f.label :Modificar, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :Modificar, :class => 'form-control' %>
      </div>
      <%= error_span(@permiso[:Modificar]) %>
    </td>
    <td class="control-group">
      <%= f.label :Ver, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :Ver, :class => 'form-control' %>
      </div>
      <%= error_span(@permiso[:Ver]) %>
    </td>
    <td class="control-group">
      <%= f.label :rols_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :rols_id, Rol.all.collect { |p| [ p.NombreRol, p.id ] } %>
      </div>
      <%= error_span(@permiso[:rols_id]) %>
    </td>
  </tr>
</table>

<%= f.submit nil, :class => 'btn btn-primary' %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        permisos_path, :class => 'btn btn-default' %>
<% end %>

app/views/permisos/edit.html.erb
<%- model_class = Permiso -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/permisos/index.html.erb
<%- model_class = Permiso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
    <table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:NombrePermiso) %></th>
      <th><%= model_class.human_attribute_name(:Eliminar) %></th>
      <th><%= model_class.human_attribute_name(:Modificar) %></th>
      <th><%= model_class.human_attribute_name(:Ver) %></th>
      <th><%= model_class.human_attribute_name(:rols_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @permisos.each do |permiso| %>
      <tr>
        <td><%= link_to permiso.id, permiso_path(permiso) %></td>
        <td><%= permiso.NombrePermiso %></td>
        <td><%= permiso.Eliminar %></td>
        <td><%= permiso.Modificar %></td>
        <td><%= permiso.Ver %></td>
        <td><%= permiso.rols_id %></td>
        <td><%= permiso.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_permiso_path(permiso), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      permiso_path(permiso),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_permiso_path,
            :class => 'btn btn-primary' %>

app/views/permisos/new.html.erb
<%- model_class = Permiso -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/permisos/show.html.erb
<%- model_class = Permiso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:NombrePermiso) %>:</strong></dt>
  <dd><%= @permiso.NombrePermiso %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Eliminar) %>:</strong></dt>
  <dd><%= @permiso.Eliminar %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Modificar) %>:</strong></dt>
  <dd><%= @permiso.Modificar %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Ver) %>:</strong></dt>
  <dd><%= @permiso.Ver %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rols_id) %>:</strong></dt>
  <dd><%= @permiso.rols_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              permisos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_permiso_path(@permiso), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              permiso_path(@permiso),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>