config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios

  resources :home, only: [:index]

  authenticate :usuario do
    resources :detalle_sumistros, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :municipios, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :mesas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :rols, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :departamentos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :permisos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :nombre_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :valor_nutricionals, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :suministros, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :unidad_medidas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :empresas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_menu_dia, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :menu_dia, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :clientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :estado_pedidos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :empleados, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :personas, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :departamentos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :ciudads, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :ingredientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :detalle_platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tipo_ingredientes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :platos, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :imagens, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tipo_platos, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'welcome/index'
  root 'static_pages#home'

end

app/models/nombre_nutricional.rb
class NombreNutricional < ActiveRecord::Base
  validates :NombresNutricional, presence: { message: " es requerido"}
end

app/controllers/nombre_nutricionals_controller.rb
class NombreNutricionalsController < ApplicationController
  before_action :set_nombre_nutricional, only: [:show, :edit, :update, :destroy]

  # GET /nombre_nutricionals
  # GET /nombre_nutricionals.json
  def index
    @nombre_nutricionals = NombreNutricional.all
  end

  # GET /nombre_nutricionals/1
  # GET /nombre_nutricionals/1.json
  def show
  end

  # GET /nombre_nutricionals/new
  def new
    @nombre_nutricional = NombreNutricional.new
  end

  # GET /nombre_nutricionals/1/edit
  def edit
  end

  # POST /nombre_nutricionals
  # POST /nombre_nutricionals.json
  def create
    @nombre_nutricional = NombreNutricional.new(nombre_nutricional_params)

    respond_to do |format|
      if @nombre_nutricional.save
        format.html { redirect_to @nombre_nutricional, notice: 'Nombre nutricional was successfully created.' }
        format.json { render :show, status: :created, location: @nombre_nutricional }
      else
        format.html { render :new }
        format.json { render json: @nombre_nutricional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nombre_nutricionals/1
  # PATCH/PUT /nombre_nutricionals/1.json
  def update
    respond_to do |format|
      if @nombre_nutricional.update(nombre_nutricional_params)
        format.html { redirect_to @nombre_nutricional, notice: 'Nombre nutricional was successfully updated.' }
        format.json { render :show, status: :ok, location: @nombre_nutricional }
      else
        format.html { render :edit }
        format.json { render json: @nombre_nutricional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nombre_nutricionals/1
  # DELETE /nombre_nutricionals/1.json
  def destroy
    @nombre_nutricional.destroy
    respond_to do |format|
      format.html { redirect_to nombre_nutricionals_url, notice: 'Nombre nutricional was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nombre_nutricional
      @nombre_nutricional = NombreNutricional.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nombre_nutricional_params
      params.require(:nombre_nutricional).permit(:NombresNutricional)
    end
end

app/helpers/nombre_nutricionals_helper.rb
module NombreNutricionalsHelper
end

app/views/nombre_nutricionals/_form.html.erb
<%= form_for @nombre_nutricional, :html => { :class => "form-horizontal nombre_nutricional" } do |f| %>

    <% if @nombre_nutricional.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@nombre_nutricional.errors.count, "error") %> prohibited this nombre_nutricional from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @nombre_nutricional.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :NombresNutricional, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :NombresNutricional, :class => 'form-control' %>
    </div>
    <%= error_span(@nombre_nutricional[:NombresNutricional]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            nombre_nutricionals_path, :class => 'btn btn-default' %>

<% end %>

app/views/nombre_nutricionals/edit.html.erb
<%- model_class = NombreNutricional -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nombre_nutricionals/index.html.erb
<%- model_class = NombreNutricional -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:NombresNutricional) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @nombre_nutricionals.each do |nombre_nutricional| %>
      <tr>
        <td><%= link_to nombre_nutricional.id, nombre_nutricional_path(nombre_nutricional) %></td>
        <td><%= nombre_nutricional.NombresNutricional %></td>
        <td><%= nombre_nutricional.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_nombre_nutricional_path(nombre_nutricional), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      nombre_nutricional_path(nombre_nutricional),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_nombre_nutricional_path,
            :class => 'btn btn-primary' %>

app/views/nombre_nutricionals/new.html.erb
<%- model_class = NombreNutricional -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nombre_nutricionals/show.html.erb
<%- model_class = NombreNutricional -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:NombresNutricional) %>:</strong></dt>
  <dd><%= @nombre_nutricional.NombresNutricional %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              nombre_nutricionals_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_nombre_nutricional_path(@nombre_nutricional), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              nombre_nutricional_path(@nombre_nutricional),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>